name: Deploy to EC2

on:
  schedule:
    - cron: "0 8 * * *"
  workflow_dispatch:

jobs:
  deploy-to-ec2:
    runs-on: ubuntu-latest

    environment: DATABASE_URL 
    env: 
      SOURCE_REPO_URL: https://github.com/Devenvaruv/crud-react-node-mySQL-source.git
      
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-session-token: ${{ secrets.AWS_SESSION_TOKEN }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Launch to EC2
        id: launch-ec2
        run: |
          INSTANCE_ID=$(aws ec2 run-instances \
            --image-id ami-05b10e08d247fb927 \
            --count 1 \
            --instance-type t2.micro \
            --key-name veckey \
            --security-group-ids sg-0ae6c1dd53518265f \
            --subnet-id subnet-091d221d42dca0d3f \
            --query 'Instances[0].InstanceId' \
            --output text)

          echo "INSTANCE_ID=$INSTANCE_ID" >> $GITHUB_ENV
          echo "Ephemeral INSTANCE_ID: $INSTANCE_ID"

          # Wait for instance to be running
          aws ec2 wait instance-running --instance-ids $INSTANCE_ID
          echo "EC2 is now running. Sleeping 10..."
          sleep 10
        
      - name: Set up SSH
        run: |
          echo "${{ secrets.EC2_SSH_KEY }}" > veckey.pem
          chmod 400 veckey.pem
      - name: get temp EC2 Hostname
        id: get_temp_ec2
        run: |
          PUBLIC_DNS=$(aws ec2 describe-instances \
            --instance-ids "${{ env.INSTANCE_ID }}" \
            --query 'Reservations[0].Instances[0].PublicDnsName' \
            --output text)
          echo "PUBLIC_DNS=$PUBLIC_DNS" >> $GITHUB_ENV
          echo "::set-output name=public_dns::$PUBLIC_DNS"
          echo "Ephemeral EC2 Hostname: $PUBLIC_DNS"
      - name: Install Docker on  EC2
        run: |
          TEMP_HOST="${{ steps.get_temp_ec2.outputs.public_dns }}"
          echo " SSH into ephemeral EC2 at $TEMP_HOST to install Docker..."

          ssh -o StrictHostKeyChecking=no -i veckey.pem ec2-user@"$TEMP_HOST" << 'EOF'
            set -e
            echo "Connected to ephemeral EC2. Installing Docker + Docker Compose..."
            sudo yum update -y
            sudo yum install -y docker git jq
            sudo service docker start
            sudo usermod -aG docker ec2-user
            
            # Install Docker Compose
            sudo curl -L \
              "https://github.com/docker/compose/releases/latest/download/docker-compose-$(uname -s)-$(uname -m)" \
              -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose
            
            echo "Docker version:"
            docker --version
            echo "Docker Compose version:"
            docker-compose --version
            
            mkdir -p ~/env_files
          EOF
      - name: Setup Environment Files
        run: |
          TEMP_HOST="${{ steps.get_temp_ec2.outputs.public_dns }}"

          # Test database connectivity
          # Correct way to test database connectivity
          
          
          # Create .env file content locally
          cat > .env << EOF
          DB_HOST=${{ secrets.RDS_ENDPOINT }}
          DB_USER=${{ secrets.RDS_USERNAME }}
          DB_PASSWORD=${{ secrets.RDS_PASSWORD }}
          DB_NAME=${{ secrets.RDS_DBNAME }}
          DB_PORT=3306
          EOF
          source .env
          # Create AWS credentials file
          cat > aws_creds.sh << EOF
          export AWS_REGION=${{ secrets.AWS_REGION }}
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
          export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
          export SOURCE_REPO_URL=${{ secrets.SOURCE_REPO_URL }}
          EOF
          
          # Create a simplified nginx test configuration
          cat > nginx_conf.txt << 'EOF'
          server {
              listen 80;
              server_name localhost;

              # Proxy /api requests to backend
              location /api/ {
                proxy_pass http://my_backend:8800/;
                proxy_http_version 1.1;
                proxy_set_header Upgrade $http_upgrade;
                proxy_set_header Connection 'upgrade';
                proxy_set_header Host $host;
                proxy_cache_bypass $http_upgrade;
              }
          
              # React fallback
              location / {
                  root /usr/share/nginx/html;
                  try_files $uri /index.html;
              }
          }
          EOF
          # Add to your build_test_ec2 script

          # Create a docker-compose test override
          cat > docker_compose_test_override.txt << 'EOF'
          version: "3.9"
          
          services:
            test_nginx:
              image: nginx:latest
              container_name: nginx
              ports:
                - "80:80"
              volumes:
                - ./nginx-test-conf/default.conf:/etc/nginx/conf.d/default.conf:ro
              command: [nginx-debug, '-g', 'daemon off;']  
              depends_on:
                - backend
                - frontend
          EOF
          
          # Create enhanced smoke test script with debugging and retries
          cat > smoke_tests.sh << 'EOF'
          #!/bin/bash
          set -e

          # Function to retry HTTP requests with timeout
          function retry_curl() {
            local URL=$1
            local MAX_RETRIES=5
            local RETRY_DELAY=5
            local COUNT=0
            local EXIT_CODE=0
            local RESPONSE=""

            echo "Attempting to connect to $URL (with retries)..."
            
            until [ $COUNT -ge $MAX_RETRIES ]; do
              RESPONSE=$(curl -i -s -L -k $URL --max-time 10 || echo "CURL_FAILED")
              
              if [[ "$RESPONSE" != "CURL_FAILED" ]] && [[ "$RESPONSE" == *"200 OK"* ]]; then
                echo "Successfully connected to $URL on attempt $((COUNT+1))"
                echo "$RESPONSE" > /tmp/curl_response.txt
                return 0
              fi
              
              echo "attempt $((COUNT+1)) failed - waiting ${RETRY_DELAY}s before retrying..."
              sleep $RETRY_DELAY
              COUNT=$((COUNT+1))
            done
            
            echo "Failed to connect to $URL after $MAX_RETRIES attempts"
            return 1
          }

          docker logs nginx || echo "Could not get nginx logs"
          
          echo "Displaying backend container"
          docker logs my_backend || echo "Could not get backend logs"

          # (B) Check the API endpoint
          echo "--- Checking backend API: GET /api/books ---"
          if retry_curl "http://localhost/api/books"; then
            HTTP_API=$(cat /tmp/curl_response.txt)
            echo "$HTTP_API" | grep -q "200 OK"
            JSON_BODY=$(echo "$HTTP_API" | awk '/^\[|^\{/{flag=1} flag{print}')
            if [[ "$JSON_BODY" =~ ^(\[|\{) ]]; then
              echo "/api/books endpoint returned 200 and valid JSON"
              echo "JSON response: $JSON_BODY"
            else
              echo "/api/books returned 200 but did not contain JSON"
              exit 1
            fi
          else
            echo "Failed to connect to API endpoint"
            exit 1
          fi

          echo "all smoke tests passed successfully!"
          EOF
          
          # Copy files to EC2 instance
          scp -o StrictHostKeyChecking=no -i veckey.pem .env ec2-user@"$TEMP_HOST":~/env_files/
          scp -o StrictHostKeyChecking=no -i veckey.pem aws_creds.sh ec2-user@"$TEMP_HOST":~/env_files/
          scp -o StrictHostKeyChecking=no -i veckey.pem smoke_tests.sh ec2-user@"$TEMP_HOST":~/env_files/
          scp -o StrictHostKeyChecking=no -i veckey.pem nginx_conf.txt ec2-user@"$TEMP_HOST":~/env_files/
          scp -o StrictHostKeyChecking=no -i veckey.pem docker_compose_test_override.txt ec2-user@"$TEMP_HOST":~/env_files/
          
          # Make smoke test script executable
          ssh -o StrictHostKeyChecking=no -i veckey.pem ec2-user@"$TEMP_HOST" "chmod +x ~/env_files/smoke_tests.sh"


      - name: Build & Test on C2
        id: build_test_ec2
        run: |
          TEMP_HOST="${{ steps.get_temp_ec2.outputs.public_dns }}"
          echo "SSHinto ephemeral EC2 at $TEMP_HOST for build and test..."

          ssh -o StrictHostKeyChecking=no -i veckey.pem ec2-user@"$TEMP_HOST" << 'EOF'
            set -e
            
            source ~/env_files/aws_creds.sh
            
            # Log into ECR
            aws ecr get-login-password --region ${AWS_REGION} \
              | docker login --username AWS --password-stdin ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com

            # Clone the source repo
            git clone ${SOURCE_REPO_URL} source
            cd source
            
            # Set up test nginx configuration
            mkdir -p nginx-test-conf
            cp ~/env_files/nginx_conf.txt nginx-test-conf/default.conf
            cp ~/env_files/docker_compose_test_override.txt docker-compose.test.yml
            
            # Copy the .env file
            cp ~/env_files/.env .

            
            docker-compose -f docker-compose.yml --env-file .env build
            
            echo "Starting containers with docker-compose and test override..."
            docker-compose -f docker-compose.yml -f docker-compose.test.yml --env-file .env up -d backend frontend test_nginx
            
            echo "Checking container names that were created:"
            docker ps
            echo "Waiting 10s for containers to initialize..."
            sleep 10
            
            ~/env_files/smoke_tests.sh
            
            # Stop containers
            docker-compose -f docker-compose.yml -f docker-compose.test.yml --env-file .env down
            
            # Tag and push to ECR
            echo "Identifying built images..."
            
            FRONTEND_IMAGE_ID=$(docker images --filter=reference="source-frontend" --format "{{.ID}}")
            BACKEND_IMAGE_ID=$(docker images --filter=reference="source-backend" --format "{{.ID}}")
            
            if [ -z "$FRONTEND_IMAGE_ID" ] || [ -z "$BACKEND_IMAGE_ID" ]; then
              echo "not find built front or backend!!!!!"
              exit 1
            fi
            
            TIMESTAMP=$(date "+%Y%m%d.%H%M%S")
            echo "Found images. Using TIMESTAMP $TIMESTAMP for tagging."
            
            # Tag and push frontend
            docker tag "$FRONTEND_IMAGE_ID" ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_frontend:frontend-$TIMESTAMP
            docker tag "$FRONTEND_IMAGE_ID" ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_frontend:latest
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_frontend:frontend-$TIMESTAMP
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_frontend:latest
   
            docker tag "$BACKEND_IMAGE_ID" ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_backend:backend-$TIMESTAMP
            docker tag "$BACKEND_IMAGE_ID" ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_backend:latest
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_backend:backend-$TIMESTAMP
            docker push ${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_REGION}.amazonaws.com/crud_backend:latest
            
            echo "tested + pushed to ECR succeeded."
          EOF
      - name: Deploy to QA EC2
        if: success()
        run: |
          echo "Smoke test  succeeded. Deploying latest images to QA..."
          
          # Create ECR-specific docker-compose file locally
          cat > docker-compose.ecr.yml << EOF
          version: "3.9"
          services:
            backend:
              image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/crud_backend
              container_name: my_backend
              expose:
                - "8800"
              environment:
                - DB_HOST=\${DB_HOST}
                - DB_USER=\${DB_USER}
                - DB_PASSWORD=\${DB_PASSWORD}
                - DB_NAME=\${DB_NAME}
                - DB_PORT=\${DB_PORT}
            frontend:
              image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ env.AWS_REGION }}.amazonaws.com/crud_frontend
              container_name: my_frontend
              ports:
                - "80:80"
                - "443:443"
              depends_on:
                - backend
              volumes:
                - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
          EOF
          
          # Copy the file to QA server
          scp -o StrictHostKeyChecking=no -i veckey.pem \
            docker-compose.ecr.yml \
            ec2-user@${{ secrets.EC2_PUBLIC_DNS }}:/home/ec2-user/crud-react-node-mySQL-go/docker-compose.ecr.yml
          
          # Deploy using the ECR config
          ssh -o StrictHostKeyChecking=no -i veckey.pem ec2-user@${{ secrets.EC2_PUBLIC_DNS }} << EOF
            export AWS_REGION=${{ env.AWS_REGION }}
            export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
            export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
            export AWS_SESSION_TOKEN=${{ secrets.AWS_SESSION_TOKEN }}
            export AWS_ACCOUNT_ID=${{ secrets.AWS_ACCOUNT_ID }}
            
            # Re-log into ECR
            aws ecr get-login-password --region \${AWS_REGION} \
              | docker login --username AWS --password-stdin \${AWS_ACCOUNT_ID}.dkr.ecr.\${AWS_REGION}.amazonaws.com

            docker-compose \
              -f /home/ec2-user/crud-react-node-mySQL-go/docker-compose.prod.yml \
              --env-file /home/ec2-user/crud-react-node-mySQL-go/.env down -v

            docker rmi crud_frontend crud_backend || true
            
            # Pull the new images
            docker pull \${AWS_ACCOUNT_ID}.dkr.ecr.\${AWS_REGION}.amazonaws.com/crud_frontend
            docker pull \${AWS_ACCOUNT_ID}.dkr.ecr.\${AWS_REGION}.amazonaws.com/crud_backend
            
            docker-compose \
              -f /home/ec2-user/crud-react-node-mySQL-go/docker-compose.ecr.yml \
              --env-file /home/ec2-user/crud-react-node-mySQL-go/.env up -d

            docker ps
            
            # Clean up old images
            docker image prune -f
            docker-compose down
            docker-compose up -d
            echo "Deployed to QA EC2 successfully."
          EOF
